### ISSUE TITLE
SenSayQ Ransom Note

### ISSUE THREAD

**Issue by FafnerKeyZee** [threatlabz/ransomware_notes#4]
Hello,

Please find the Ransom note for SenSayQ. Extracted from this sample: 8ea416fd97ba762b5fa6519906c56f6c98f078f398ff75be7ed43fa1cc5313a9

[523XaDi1i.README.txt](https://github.com/user-attachments/files/15580685/523XaDi1i.README.txt)

Regards,

**Comment by ThreatLabz** [comment]
Added. Thank you!
