### ISSUE TITLE
Risen Ransomware 

### ISSUE THREAD

**Issue by FafnerKeyZee** [threatlabz/ransomware_notes#5]
Hello,

New ransomnote for Risen Ransomware, based on this sample:
3b685f4a59211225997256a5cd900f44953bba276b6eb92545966b35b6ef89b5

[$Risen_Note.txt](https://github.com/user-attachments/files/15623547/Risen_Note.txt)
and HTA file (please rename to hta)
[$Risen_Guide.hta.txt](https://github.com/user-attachments/files/15624047/Risen_Guide.hta.txt)

Regards,

**Comment by FafnerKeyZee** [comment]
Alternative hta (other DLS)
[$Risen_Guide.hta.V2.txt](https://github.com/user-attachments/files/15624919/Risen_Guide.hta.V2.txt)

**Comment by ThreatLabz** [comment]
Added. Thank you @FafnerKeyZee!
