### ISSUE TITLE
Interlock

### ISSUE THREAD

**Issue by FafnerKeyZee** [threatlabz/ransomware_notes#8]
Hello,

Please find the ransomnote for Interlock: 

Filename: !__README__!.txt
Sample: https://www.virustotal.com/gui/file/e86bb8361c436be94b0901e5b39db9b6666134f23cce1e5581421c2981405cb1
[!__README__!.txt](https://github.com/user-attachments/files/17311242/__README__.txt)

**Comment by ThreatLabz** [comment]
Added. Thank you!
